/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author Joao
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        labelTitle1 = new javax.swing.JLabel();
        labelTitle2 = new javax.swing.JLabel();
        labelTitle3 = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        tfEquipeB = new javax.swing.JTextField();
        tfHorario = new javax.swing.JTextField();
        tfEquipeA = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(51, 153, 0));
        labelTitle.setText("EQUIPE B");
        getContentPane().add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        labelTitle1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        labelTitle1.setForeground(new java.awt.Color(51, 153, 0));
        labelTitle1.setText("PLACAR DE VÔLEI - UDESC");
        getContentPane().add(labelTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        labelTitle2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        labelTitle2.setForeground(new java.awt.Color(51, 153, 0));
        labelTitle2.setText("HORÁRIO");
        getContentPane().add(labelTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        labelTitle3.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        labelTitle3.setForeground(new java.awt.Color(51, 153, 0));
        labelTitle3.setText("EQUIPE A");
        getContentPane().add(labelTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        btnContinuar.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(0, 153, 0));
        btnContinuar.setText("CONTINUAR");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, -1));

        tfEquipeB.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        tfEquipeB.setForeground(new java.awt.Color(0, 153, 0));
        tfEquipeB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tfEquipeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 190, -1));

        tfHorario.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        tfHorario.setForeground(new java.awt.Color(0, 153, 0));
        tfHorario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tfHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 180, 190, -1));

        tfEquipeA.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        tfEquipeA.setForeground(new java.awt.Color(0, 153, 0));
        tfEquipeA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tfEquipeA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 190, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed

        String horario = tfHorario.getText();
        String equipeA = tfEquipeA.getText();
        String equipeB = tfEquipeB.getText();

        String erro = "";
        
        if (equipeA.equals(equipeB)) {
            erro = "Nomes das equipes devem ser diferentes!";
        }
        
        if (horario.equals("") || equipeA.equals("") || equipeB.equals("")) {
            erro = "Todos os campos devem ser preenchidos!";
        }

        if (erro.equals("")) {
            TelaPlacar telaPlacar = new TelaPlacar(horario, equipeA, equipeB);
            this.setVisible(false);
            telaPlacar.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, erro);
        }

    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTitle1;
    private javax.swing.JLabel labelTitle2;
    private javax.swing.JLabel labelTitle3;
    private javax.swing.JTextField tfEquipeA;
    private javax.swing.JTextField tfEquipeB;
    private javax.swing.JTextField tfHorario;
    // End of variables declaration//GEN-END:variables
}
